# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ppp.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(675, 481)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 661, 421))
        self.tabWidget.setObjectName("tabWidget")
        self.System = QtWidgets.QWidget()
        self.System.setObjectName("System")
        self.c_CLK = QtWidgets.QComboBox(self.System)
        self.c_CLK.setGeometry(QtCore.QRect(360, 50, 111, 20))
        self.c_CLK.setObjectName("c_CLK")
        self.label = QtWidgets.QLabel(self.System)
        self.label.setGeometry(QtCore.QRect(205, 50, 61, 16))
        self.label.setObjectName("label")
        self.b_CLK = QtWidgets.QCheckBox(self.System)
        self.b_CLK.setGeometry(QtCore.QRect(51, 51, 70, 17))
        self.b_CLK.setObjectName("b_CLK")
        self.b_WAKEUP = QtWidgets.QCheckBox(self.System)
        self.b_WAKEUP.setGeometry(QtCore.QRect(31, 281, 92, 17))
        self.b_WAKEUP.setObjectName("b_WAKEUP")
        self.label_2 = QtWidgets.QLabel(self.System)
        self.label_2.setGeometry(QtCore.QRect(185, 280, 103, 16))
        self.label_2.setObjectName("label_2")
        self.c_WAKEUP = QtWidgets.QComboBox(self.System)
        self.c_WAKEUP.setGeometry(QtCore.QRect(340, 280, 121, 20))
        self.c_WAKEUP.setObjectName("c_WAKEUP")
        self.b_CLKOUT = QtWidgets.QCheckBox(self.System)
        self.b_CLKOUT.setGeometry(QtCore.QRect(51, 121, 92, 17))
        self.b_CLKOUT.setObjectName("b_CLKOUT")
        self.c_CLKOUT = QtWidgets.QComboBox(self.System)
        self.c_CLKOUT.setGeometry(QtCore.QRect(360, 120, 121, 20))
        self.c_CLKOUT.setObjectName("c_CLKOUT")
        self.label_3 = QtWidgets.QLabel(self.System)
        self.label_3.setGeometry(QtCore.QRect(205, 120, 103, 16))
        self.label_3.setObjectName("label_3")
        self.c_WDT = QtWidgets.QComboBox(self.System)
        self.c_WDT.setGeometry(QtCore.QRect(359, 179, 121, 20))
        self.c_WDT.setObjectName("c_WDT")
        self.label_4 = QtWidgets.QLabel(self.System)
        self.label_4.setGeometry(QtCore.QRect(204, 179, 103, 16))
        self.label_4.setObjectName("label_4")
        self.b_WDT = QtWidgets.QCheckBox(self.System)
        self.b_WDT.setGeometry(QtCore.QRect(50, 180, 92, 17))
        self.b_WDT.setObjectName("b_WDT")
        self.label_5 = QtWidgets.QLabel(self.System)
        self.label_5.setGeometry(QtCore.QRect(140, 220, 41, 31))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.System)
        self.label_7.setGeometry(QtCore.QRect(190, 320, 141, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.System)
        self.label_8.setGeometry(QtCore.QRect(320, 210, 31, 31))
        self.label_8.setObjectName("label_8")
        self.c_WDT_TIMEOUT = QtWidgets.QComboBox(self.System)
        self.c_WDT_TIMEOUT.setGeometry(QtCore.QRect(190, 220, 121, 20))
        self.c_WDT_TIMEOUT.setObjectName("c_WDT_TIMEOUT")
        self.groupBox_6 = QtWidgets.QGroupBox(self.System)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 20, 591, 16))
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_7 = QtWidgets.QGroupBox(self.System)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 100, 591, 16))
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_8 = QtWidgets.QGroupBox(self.System)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 160, 601, 16))
        self.groupBox_8.setObjectName("groupBox_8")
        self.groupBox_9 = QtWidgets.QGroupBox(self.System)
        self.groupBox_9.setGeometry(QtCore.QRect(20, 260, 601, 16))
        self.groupBox_9.setObjectName("groupBox_9")
        self.tabWidget.addTab(self.System, "")
        self.GPIO = QtWidgets.QWidget()
        self.GPIO.setObjectName("GPIO")
        self.t_GPIO = QtWidgets.QTableWidget(self.GPIO)
        self.t_GPIO.setGeometry(QtCore.QRect(140, 0, 371, 401))
        self.t_GPIO.setObjectName("t_GPIO")
        self.t_GPIO.setColumnCount(0)
        self.t_GPIO.setRowCount(0)
        self.b_GPIO = QtWidgets.QCheckBox(self.GPIO)
        self.b_GPIO.setGeometry(QtCore.QRect(20, 10, 91, 16))
        self.b_GPIO.setObjectName("b_GPIO")
        self.tabWidget.addTab(self.GPIO, "")
        self.GPIO_INTERRUPT = QtWidgets.QWidget()
        self.GPIO_INTERRUPT.setObjectName("GPIO_INTERRUPT")
        self.lab_9 = QtWidgets.QLabel(self.GPIO_INTERRUPT)
        self.lab_9.setGeometry(QtCore.QRect(170, 40, 91, 16))
        self.lab_9.setObjectName("lab_9")
        self.c_INT0 = QtWidgets.QComboBox(self.GPIO_INTERRUPT)
        self.c_INT0.setGeometry(QtCore.QRect(329, 39, 111, 20))
        self.c_INT0.setObjectName("c_INT0")
        self.b_INT0 = QtWidgets.QCheckBox(self.GPIO_INTERRUPT)
        self.b_INT0.setGeometry(QtCore.QRect(20, 40, 131, 17))
        self.b_INT0.setObjectName("b_INT0")
        self.c_INT1 = QtWidgets.QComboBox(self.GPIO_INTERRUPT)
        self.c_INT1.setGeometry(QtCore.QRect(329, 139, 111, 20))
        self.c_INT1.setObjectName("c_INT1")
        self.lab_10 = QtWidgets.QLabel(self.GPIO_INTERRUPT)
        self.lab_10.setGeometry(QtCore.QRect(170, 140, 91, 16))
        self.lab_10.setObjectName("lab_10")
        self.b_INT1 = QtWidgets.QCheckBox(self.GPIO_INTERRUPT)
        self.b_INT1.setGeometry(QtCore.QRect(20, 140, 131, 17))
        self.b_INT1.setObjectName("b_INT1")
        self.lab_11 = QtWidgets.QLabel(self.GPIO_INTERRUPT)
        self.lab_11.setGeometry(QtCore.QRect(170, 70, 91, 16))
        self.lab_11.setObjectName("lab_11")
        self.lab_12 = QtWidgets.QLabel(self.GPIO_INTERRUPT)
        self.lab_12.setGeometry(QtCore.QRect(170, 170, 91, 16))
        self.lab_12.setObjectName("lab_12")
        self.c_INT0_PINSELECT = QtWidgets.QComboBox(self.GPIO_INTERRUPT)
        self.c_INT0_PINSELECT.setGeometry(QtCore.QRect(330, 70, 111, 20))
        self.c_INT0_PINSELECT.setObjectName("c_INT0_PINSELECT")
        self.c_INT1_PINSELECT = QtWidgets.QComboBox(self.GPIO_INTERRUPT)
        self.c_INT1_PINSELECT.setGeometry(QtCore.QRect(330, 170, 111, 20))
        self.c_INT1_PINSELECT.setObjectName("c_INT1_PINSELECT")
        self.b_PININT = QtWidgets.QCheckBox(self.GPIO_INTERRUPT)
        self.b_PININT.setGeometry(QtCore.QRect(30, 240, 131, 17))
        self.b_PININT.setObjectName("b_PININT")
        self.lab_13 = QtWidgets.QLabel(self.GPIO_INTERRUPT)
        self.lab_13.setGeometry(QtCore.QRect(180, 240, 91, 16))
        self.lab_13.setObjectName("lab_13")
        self.c_PIN_INT_PORT = QtWidgets.QComboBox(self.GPIO_INTERRUPT)
        self.c_PIN_INT_PORT.setGeometry(QtCore.QRect(339, 239, 111, 20))
        self.c_PIN_INT_PORT.setObjectName("c_PIN_INT_PORT")
        self.lab_14 = QtWidgets.QLabel(self.GPIO_INTERRUPT)
        self.lab_14.setGeometry(QtCore.QRect(30, 280, 47, 13))
        self.lab_14.setObjectName("lab_14")
        self.c_PIN0 = QtWidgets.QComboBox(self.GPIO_INTERRUPT)
        self.c_PIN0.setGeometry(QtCore.QRect(80, 280, 91, 22))
        self.c_PIN0.setObjectName("c_PIN0")
        self.c_PIN1 = QtWidgets.QComboBox(self.GPIO_INTERRUPT)
        self.c_PIN1.setGeometry(QtCore.QRect(230, 280, 91, 22))
        self.c_PIN1.setObjectName("c_PIN1")
        self.lab_15 = QtWidgets.QLabel(self.GPIO_INTERRUPT)
        self.lab_15.setGeometry(QtCore.QRect(180, 280, 47, 13))
        self.lab_15.setObjectName("lab_15")
        self.c_PIN2 = QtWidgets.QComboBox(self.GPIO_INTERRUPT)
        self.c_PIN2.setGeometry(QtCore.QRect(380, 280, 91, 22))
        self.c_PIN2.setObjectName("c_PIN2")
        self.lab_16 = QtWidgets.QLabel(self.GPIO_INTERRUPT)
        self.lab_16.setGeometry(QtCore.QRect(330, 280, 47, 13))
        self.lab_16.setObjectName("lab_16")
        self.lab_17 = QtWidgets.QLabel(self.GPIO_INTERRUPT)
        self.lab_17.setGeometry(QtCore.QRect(480, 280, 47, 13))
        self.lab_17.setObjectName("lab_17")
        self.c_PIN3 = QtWidgets.QComboBox(self.GPIO_INTERRUPT)
        self.c_PIN3.setGeometry(QtCore.QRect(530, 280, 91, 22))
        self.c_PIN3.setObjectName("c_PIN3")
        self.c_PIN4 = QtWidgets.QComboBox(self.GPIO_INTERRUPT)
        self.c_PIN4.setGeometry(QtCore.QRect(80, 320, 91, 22))
        self.c_PIN4.setObjectName("c_PIN4")
        self.lab_18 = QtWidgets.QLabel(self.GPIO_INTERRUPT)
        self.lab_18.setGeometry(QtCore.QRect(30, 320, 47, 13))
        self.lab_18.setObjectName("lab_18")
        self.lab_19 = QtWidgets.QLabel(self.GPIO_INTERRUPT)
        self.lab_19.setGeometry(QtCore.QRect(330, 320, 47, 13))
        self.lab_19.setObjectName("lab_19")
        self.c_PIN6 = QtWidgets.QComboBox(self.GPIO_INTERRUPT)
        self.c_PIN6.setGeometry(QtCore.QRect(380, 320, 91, 22))
        self.c_PIN6.setObjectName("c_PIN6")
        self.c_PIN7 = QtWidgets.QComboBox(self.GPIO_INTERRUPT)
        self.c_PIN7.setGeometry(QtCore.QRect(530, 320, 91, 22))
        self.c_PIN7.setObjectName("c_PIN7")
        self.c_PIN5 = QtWidgets.QComboBox(self.GPIO_INTERRUPT)
        self.c_PIN5.setGeometry(QtCore.QRect(230, 320, 91, 22))
        self.c_PIN5.setObjectName("c_PIN5")
        self.lab_20 = QtWidgets.QLabel(self.GPIO_INTERRUPT)
        self.lab_20.setGeometry(QtCore.QRect(480, 320, 47, 13))
        self.lab_20.setObjectName("lab_20")
        self.lab_21 = QtWidgets.QLabel(self.GPIO_INTERRUPT)
        self.lab_21.setGeometry(QtCore.QRect(180, 320, 47, 13))
        self.lab_21.setObjectName("lab_21")
        self.groupBox_3 = QtWidgets.QGroupBox(self.GPIO_INTERRUPT)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 220, 621, 16))
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.GPIO_INTERRUPT)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 110, 621, 16))
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.GPIO_INTERRUPT)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 621, 16))
        self.groupBox_5.setObjectName("groupBox_5")
        self.tabWidget.addTab(self.GPIO_INTERRUPT, "")
        self.Timer0 = QtWidgets.QWidget()
        self.Timer0.setObjectName("Timer0")
        self.b_Timer0 = QtWidgets.QCheckBox(self.Timer0)
        self.b_Timer0.setGeometry(QtCore.QRect(30, 20, 131, 17))
        self.b_Timer0.setObjectName("b_Timer0")
        self.lab_22 = QtWidgets.QLabel(self.Timer0)
        self.lab_22.setGeometry(QtCore.QRect(151, 21, 91, 16))
        self.lab_22.setObjectName("lab_22")
        self.lab_23 = QtWidgets.QLabel(self.Timer0)
        self.lab_23.setGeometry(QtCore.QRect(151, 51, 91, 16))
        self.lab_23.setObjectName("lab_23")
        self.c_Timer0_Mode = QtWidgets.QComboBox(self.Timer0)
        self.c_Timer0_Mode.setGeometry(QtCore.QRect(311, 51, 111, 20))
        self.c_Timer0_Mode.setObjectName("c_Timer0_Mode")
        self.c_Timer0 = QtWidgets.QComboBox(self.Timer0)
        self.c_Timer0.setGeometry(QtCore.QRect(310, 20, 111, 20))
        self.c_Timer0.setObjectName("c_Timer0")
        self.label_17 = QtWidgets.QLabel(self.Timer0)
        self.label_17.setGeometry(QtCore.QRect(50, 110, 47, 13))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.Timer0)
        self.label_18.setGeometry(QtCore.QRect(50, 140, 47, 13))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.Timer0)
        self.label_19.setGeometry(QtCore.QRect(50, 170, 47, 13))
        self.label_19.setObjectName("label_19")
        self.tabWidget.addTab(self.Timer0, "")
        self.Timer1 = QtWidgets.QWidget()
        self.Timer1.setObjectName("Timer1")
        self.c_Timer1_Mode = QtWidgets.QComboBox(self.Timer1)
        self.c_Timer1_Mode.setGeometry(QtCore.QRect(331, 91, 111, 20))
        self.c_Timer1_Mode.setObjectName("c_Timer1_Mode")
        self.lab_24 = QtWidgets.QLabel(self.Timer1)
        self.lab_24.setGeometry(QtCore.QRect(171, 91, 91, 16))
        self.lab_24.setObjectName("lab_24")
        self.lab_25 = QtWidgets.QLabel(self.Timer1)
        self.lab_25.setGeometry(QtCore.QRect(171, 61, 91, 16))
        self.lab_25.setObjectName("lab_25")
        self.c_Timer1 = QtWidgets.QComboBox(self.Timer1)
        self.c_Timer1.setGeometry(QtCore.QRect(330, 60, 111, 20))
        self.c_Timer1.setObjectName("c_Timer1")
        self.b_Timer1 = QtWidgets.QCheckBox(self.Timer1)
        self.b_Timer1.setGeometry(QtCore.QRect(50, 60, 131, 17))
        self.b_Timer1.setObjectName("b_Timer1")
        self.tabWidget.addTab(self.Timer1, "")
        self.Timer3 = QtWidgets.QWidget()
        self.Timer3.setObjectName("Timer3")
        self.c_Timer3 = QtWidgets.QComboBox(self.Timer3)
        self.c_Timer3.setGeometry(QtCore.QRect(340, 50, 111, 20))
        self.c_Timer3.setObjectName("c_Timer3")
        self.b_Timer3 = QtWidgets.QCheckBox(self.Timer3)
        self.b_Timer3.setGeometry(QtCore.QRect(60, 50, 131, 17))
        self.b_Timer3.setObjectName("b_Timer3")
        self.lab_26 = QtWidgets.QLabel(self.Timer3)
        self.lab_26.setGeometry(QtCore.QRect(181, 51, 91, 16))
        self.lab_26.setObjectName("lab_26")
        self.tabWidget.addTab(self.Timer3, "")
        self.UART = QtWidgets.QWidget()
        self.UART.setObjectName("UART")
        self.c_UART0 = QtWidgets.QComboBox(self.UART)
        self.c_UART0.setGeometry(QtCore.QRect(339, 39, 121, 20))
        self.c_UART0.setObjectName("c_UART0")
        self.label_9 = QtWidgets.QLabel(self.UART)
        self.label_9.setGeometry(QtCore.QRect(184, 39, 103, 16))
        self.label_9.setObjectName("label_9")
        self.b_UART0 = QtWidgets.QCheckBox(self.UART)
        self.b_UART0.setGeometry(QtCore.QRect(30, 40, 92, 17))
        self.b_UART0.setObjectName("b_UART0")
        self.label_10 = QtWidgets.QLabel(self.UART)
        self.label_10.setGeometry(QtCore.QRect(180, 80, 103, 16))
        self.label_10.setObjectName("label_10")
        self.c_UART0_Timer = QtWidgets.QComboBox(self.UART)
        self.c_UART0_Timer.setGeometry(QtCore.QRect(340, 80, 121, 20))
        self.c_UART0_Timer.setObjectName("c_UART0_Timer")
        self.label_11 = QtWidgets.QLabel(self.UART)
        self.label_11.setGeometry(QtCore.QRect(180, 120, 103, 16))
        self.label_11.setObjectName("label_11")
        self.c_UART0_BaudRate = QtWidgets.QComboBox(self.UART)
        self.c_UART0_BaudRate.setGeometry(QtCore.QRect(340, 120, 121, 20))
        self.c_UART0_BaudRate.setObjectName("c_UART0_BaudRate")
        self.c_UART1 = QtWidgets.QComboBox(self.UART)
        self.c_UART1.setGeometry(QtCore.QRect(349, 249, 121, 20))
        self.c_UART1.setObjectName("c_UART1")
        self.label_12 = QtWidgets.QLabel(self.UART)
        self.label_12.setGeometry(QtCore.QRect(190, 330, 103, 16))
        self.label_12.setObjectName("label_12")
        self.b_UART1 = QtWidgets.QCheckBox(self.UART)
        self.b_UART1.setGeometry(QtCore.QRect(40, 250, 92, 17))
        self.b_UART1.setObjectName("b_UART1")
        self.label_13 = QtWidgets.QLabel(self.UART)
        self.label_13.setGeometry(QtCore.QRect(194, 249, 103, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.UART)
        self.label_14.setGeometry(QtCore.QRect(190, 290, 103, 16))
        self.label_14.setObjectName("label_14")
        self.c_UART1_BaudRate = QtWidgets.QComboBox(self.UART)
        self.c_UART1_BaudRate.setGeometry(QtCore.QRect(350, 330, 121, 20))
        self.c_UART1_BaudRate.setObjectName("c_UART1_BaudRate")
        self.c_UART1_Timer = QtWidgets.QComboBox(self.UART)
        self.c_UART1_Timer.setGeometry(QtCore.QRect(350, 290, 121, 20))
        self.c_UART1_Timer.setObjectName("c_UART1_Timer")
        self.groupBox = QtWidgets.QGroupBox(self.UART)
        self.groupBox.setGeometry(QtCore.QRect(20, 220, 591, 16))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.UART)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 601, 16))
        self.groupBox_2.setObjectName("groupBox_2")
        self.tabWidget.addTab(self.UART, "")
        self.ADC = QtWidgets.QWidget()
        self.ADC.setObjectName("ADC")
        self.b_ADC = QtWidgets.QCheckBox(self.ADC)
        self.b_ADC.setGeometry(QtCore.QRect(39, 19, 131, 17))
        self.b_ADC.setObjectName("b_ADC")
        self.c_ADC = QtWidgets.QComboBox(self.ADC)
        self.c_ADC.setGeometry(QtCore.QRect(319, 19, 111, 20))
        self.c_ADC.setObjectName("c_ADC")
        self.lab_28 = QtWidgets.QLabel(self.ADC)
        self.lab_28.setGeometry(QtCore.QRect(160, 20, 91, 16))
        self.lab_28.setObjectName("lab_28")
        self.c_ADC_CH = QtWidgets.QComboBox(self.ADC)
        self.c_ADC_CH.setGeometry(QtCore.QRect(319, 69, 111, 20))
        self.c_ADC_CH.setObjectName("c_ADC_CH")
        self.lab_29 = QtWidgets.QLabel(self.ADC)
        self.lab_29.setGeometry(QtCore.QRect(160, 70, 91, 16))
        self.lab_29.setObjectName("lab_29")
        self.tabWidget.addTab(self.ADC, "")
        self.PWM = QtWidgets.QWidget()
        self.PWM.setObjectName("PWM")
        self.c_PWM = QtWidgets.QComboBox(self.PWM)
        self.c_PWM.setGeometry(QtCore.QRect(350, 30, 111, 20))
        self.c_PWM.setObjectName("c_PWM")
        self.lab_30 = QtWidgets.QLabel(self.PWM)
        self.lab_30.setGeometry(QtCore.QRect(240, 30, 91, 16))
        self.lab_30.setObjectName("lab_30")
        self.b_PWM = QtWidgets.QCheckBox(self.PWM)
        self.b_PWM.setGeometry(QtCore.QRect(70, 30, 131, 17))
        self.b_PWM.setObjectName("b_PWM")
        self.c_PWM_CH = QtWidgets.QComboBox(self.PWM)
        self.c_PWM_CH.setGeometry(QtCore.QRect(350, 80, 111, 20))
        self.c_PWM_CH.setObjectName("c_PWM_CH")
        self.label_16 = QtWidgets.QLabel(self.PWM)
        self.label_16.setGeometry(QtCore.QRect(280, 90, 47, 13))
        self.label_16.setObjectName("label_16")
        self.tabWidget.addTab(self.PWM, "")
        self.IAP = QtWidgets.QWidget()
        self.IAP.setObjectName("IAP")
        self.b_IAP_Erase = QtWidgets.QCheckBox(self.IAP)
        self.b_IAP_Erase.setGeometry(QtCore.QRect(70, 30, 141, 17))
        self.b_IAP_Erase.setObjectName("b_IAP_Erase")
        self.b_IAP_Program = QtWidgets.QCheckBox(self.IAP)
        self.b_IAP_Program.setGeometry(QtCore.QRect(70, 100, 131, 17))
        self.b_IAP_Program.setObjectName("b_IAP_Program")
        self.b_IAP_Read = QtWidgets.QCheckBox(self.IAP)
        self.b_IAP_Read.setGeometry(QtCore.QRect(70, 170, 131, 17))
        self.b_IAP_Read.setObjectName("b_IAP_Read")
        self.tabWidget.addTab(self.IAP, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.e_GEN_CODE = QtWidgets.QTextEdit(self.tab_6)
        self.e_GEN_CODE.setGeometry(QtCore.QRect(10, 10, 631, 371))
        self.e_GEN_CODE.setObjectName("e_GEN_CODE")
        self.tabWidget.addTab(self.tab_6, "")
        self.Gen_Code = QtWidgets.QPushButton(Form)
        self.Gen_Code.setGeometry(QtCore.QRect(550, 440, 75, 23))
        self.Gen_Code.setObjectName("Gen_Code")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(10)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "N76E003 Code Gen V0.01"))
        self.label.setText(_translate("Form", "Clock Source"))
        self.b_CLK.setText(_translate("Form", "CLK Initial"))
        self.b_WAKEUP.setText(_translate("Form", "WAKEUP initial"))
        self.label_2.setText(_translate("Form", "WAKEUP Mode Select"))
        self.b_CLKOUT.setText(_translate("Form", "CLKOUT initial"))
        self.label_3.setText(_translate("Form", "POLL/INTERRUPT"))
        self.label_4.setText(_translate("Form", "WDT Mode Select"))
        self.b_WDT.setText(_translate("Form", "WDT initial"))
        self.label_5.setText(_translate("Form", "Time out"))
        self.label_7.setText(_translate("Form", "100us-1638400us Timeout"))
        self.label_8.setText(_translate("Form", "us"))
        self.groupBox_6.setTitle(_translate("Form", "System Clock"))
        self.groupBox_7.setTitle(_translate("Form", "Clock Out"))
        self.groupBox_8.setTitle(_translate("Form", "WDT"))
        self.groupBox_9.setTitle(_translate("Form", "Wakeup"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.System), _translate("Form", "System"))
        self.b_GPIO.setText(_translate("Form", "GPIO INITIAL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GPIO), _translate("Form", "GPIO_MODE"))
        self.lab_9.setText(_translate("Form", "POLL/INTERRUPT"))
        self.b_INT0.setText(_translate("Form", "INT0 initial"))
        self.lab_10.setText(_translate("Form", "POLL/INTERRUPT"))
        self.b_INT1.setText(_translate("Form", "INT1 initial"))
        self.lab_11.setText(_translate("Form", "EDGE/LEVEL"))
        self.lab_12.setText(_translate("Form", "EDGE/LEVEL"))
        self.b_PININT.setText(_translate("Form", "Port Interrupt initial"))
        self.lab_13.setText(_translate("Form", "Port Select"))
        self.lab_14.setText(_translate("Form", "PIN0"))
        self.lab_15.setText(_translate("Form", "PIN1"))
        self.lab_16.setText(_translate("Form", "PIN2"))
        self.lab_17.setText(_translate("Form", "PIN3"))
        self.lab_18.setText(_translate("Form", "PIN4"))
        self.lab_19.setText(_translate("Form", "PIN6"))
        self.lab_20.setText(_translate("Form", "PIN7"))
        self.lab_21.setText(_translate("Form", "PIN5"))
        self.groupBox_3.setTitle(_translate("Form", "PIN INTERRUPT"))
        self.groupBox_4.setTitle(_translate("Form", "INT1"))
        self.groupBox_5.setTitle(_translate("Form", "INT0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GPIO_INTERRUPT), _translate("Form", "GPIO INTERRUPT"))
        self.b_Timer0.setText(_translate("Form", "Timer0 initial"))
        self.lab_22.setText(_translate("Form", "POLL/INTERRUPT"))
        self.lab_23.setText(_translate("Form", "Mode"))
        self.label_17.setText(_translate("Form", "0-512us"))
        self.label_18.setText(_translate("Form", "0-4095us"))
        self.label_19.setText(_translate("Form", "0-16us"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Timer0), _translate("Form", "Timer0"))
        self.lab_24.setText(_translate("Form", "Mode"))
        self.lab_25.setText(_translate("Form", "POLL/INTERRUPT"))
        self.b_Timer1.setText(_translate("Form", "Timer1 initial"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Timer1), _translate("Form", "Timer1"))
        self.b_Timer3.setText(_translate("Form", "Timer3 initial"))
        self.lab_26.setText(_translate("Form", "POLL/INTERRUPT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Timer3), _translate("Form", "Timer3"))
        self.label_9.setText(_translate("Form", "POLL/INTERRUPT"))
        self.b_UART0.setText(_translate("Form", "UART0 initial"))
        self.label_10.setText(_translate("Form", "Clock Source Select"))
        self.label_11.setText(_translate("Form", "BaudReate Select"))
        self.label_12.setText(_translate("Form", "BaudReate Select"))
        self.b_UART1.setText(_translate("Form", "UART1 initial"))
        self.label_13.setText(_translate("Form", "POLL/INTERRUPT"))
        self.label_14.setText(_translate("Form", "Clock Source Select"))
        self.groupBox.setTitle(_translate("Form", "UART1"))
        self.groupBox_2.setTitle(_translate("Form", "UART0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.UART), _translate("Form", "UART"))
        self.b_ADC.setText(_translate("Form", "ADC initial"))
        self.lab_28.setText(_translate("Form", "POLL/INTERRUPT"))
        self.lab_29.setText(_translate("Form", "ADC Channel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ADC), _translate("Form", "ADC"))
        self.lab_30.setText(_translate("Form", "POLL/INTERRUPT"))
        self.b_PWM.setText(_translate("Form", "PWM initial"))
        self.label_16.setText(_translate("Form", "PWM CH"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PWM), _translate("Form", "PWM"))
        self.b_IAP_Erase.setText(_translate("Form", "Erase function"))
        self.b_IAP_Program.setText(_translate("Form", "Program funciton"))
        self.b_IAP_Read.setText(_translate("Form", "Read function"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.IAP), _translate("Form", "IAP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Form", "CODE"))
        self.Gen_Code.setText(_translate("Form", "Gen Code"))

